source 'https://rubygems.org'

gem 'sass'
gem 'compass', '~> 0.13.alpha'
gem 'susy'
gem 'nanoc'
gem 'guard-nanoc'
gem 'haml'
gem 'hpricot'
gem 'pygments.rb'
gem 'pandoc-ruby'
gem 'org-ruby'
gem 'feedjira'
gem 'stringex'
gem 'summarize'
gem 'kramdown'
gem 'adsf'
gem 'systemu'
gem 'typhoeus'
gem 'slim'
gem 'rugged'
gem 'gherkin'
gem 'nokogiri'
gem 'docker-api', :require => 'docker'
gem 'mustache', :git => 'git://github.com/defunkt/mustache.git'
