---
title: Crash Course in SSH Agent Forwarding
---

* SSH Agent Forwarding
** SSH Agent
An ssh agent is a program running locally on your computer that caches
your private key after you unlock it with your password.

- Fedora
#+BEGIN_EXAMPLE
$ yum install keychain
#+END_EXAMPLE

- Ubuntu
#+BEGIN_EXAMPLE

#+END_EXAMPLE

Add the following lines to your =~/.bash_profile=, or whichever is appropriate for your shell if not =bash=

#+BEGIN_EXAMPLE
/usr/bin/keychain $HOME/.ssh/id_rsa
source $HOME/.keychain/$HOSTNAME-sh
#+END_EXAMPLE

Log out of your shell and back in. If this is the first time keychain
is runnign since boot then you will be prompted to enter your key
password.  Once you do, the unencrypted key will be cashed in memory
so you won't have to enter the password again while you remain logged
in.

Edit your =~/.ssh/config= to include the following lines

#+BEGIN_EXAMPLE
Host ece2524.ece.vt.edu
    ForwardAgent yes
#+END_EXAMPLE

Now, assuming =keychain= ran and your private key is cached, when you
=ssh= into =ece2524.ece.vt.edu= you should be able to access any
machines that your unlocked key would normally grant you access to. 
